export const SEARCH_WORD_SUCCESS = "SEARCH_WORD_SUCCESS";
export const SEARCH_WORD = "SEARCH_WORD";
export const SEARCH_WORD_ERROR = "SEARCH_WORD_ERROR";
export const SEARCH_RHYMES_SUCCESS = "SEARCH_RHYMES_SUCCESS";
export const SEARCH_RHYMES = "SEARCH_RHYMES";
